#pragma once
#include <string>

//webpage embedded into a cpp code
std::string webpage = "<!DOCTYPE html >\n"
"<html>\n"
"  <head>\n"
"    <meta charset=\"UTF-8\">\n"
"  </head>\n"
"  <body>\n"
"    <div>\n"
"      <h1 id=\"title\">FILES TO DOWNLOAD</h1>\n"
"      <button id=\"prev\" onclick=\"prev_node()\">\n"
"        Previous_dir\n"
"      </button>\n"
"      <script>\n"
"        var previous_node = [];\n"
"        function fetchJSONData() {\n"
"          fetch(\"./.download.json\").then((res) => {\n"
"            if (!res.ok)\n"
"              throw new Error (`HTTP error! Status: ${res.status}`);\n"
"            return res.json();\n"
"          })\n"
"          .then((data) => \n"
"          {\n"
"            console.log(data.url)\n"
"            previous_node.push(data);\n"
"            populateList(data);\n"
"          })\n"
"          .catch((error) => \n"
"            console.error(\"Unable to fetch data:\", error));\n"
"        }\n"
"  \n"
"        function populateList(data) {\n"
"          console.log(\"I am in populateList function\")\n"
"          var list = document.getElementById(\"list\");\n"
"          list.innerHTML = \"\"; // Clear the list\n\n"
"\n"
"          data.files.forEach(file => {\n"
"              const listItem = document.createElement(\"li\");\n"
"              const link = document.createElement(\"a\");\n"
"\n"
"              if (file.files && file.files.length !== 0) {\n"
"                // For directories\n\n"
"                link.href = \"#\";\n"
"                link.textContent = file.name + \" (Directory)\";\n"
"                link.addEventListener('click', (event) => {\n"
"                    event.preventDefault();\n"
"                    // Open the directory\n\n"
"                    previous_node.push(data);\n"
"                    populateList(file);\n"
"                });\n"
"                const downloadAllButton = document.createElement(\"button\");\n"
"                downloadAllButton.textContent = \"Download directory\";\n"
"                downloadAllButton.addEventListener('click', (event)=> {\n"
"                  event.stopPropagation();\n"
"                  downloadAllFiles(file);\n"
"                });\n"
"                listItem.appendChild(link);\n"
"                listItem.appendChild(downloadAllButton);\n"
"              } else {\n"
"                  // For files\n\n"
"                  link.href = file.url;\n"
"                  link.textContent = file.name;\n"
"                  link.setAttribute('download', '');\n"
"                  listItem.appendChild(link);\n"
"              }\n"
"              list.appendChild(listItem);\n"
"          });\n"
"        }\n"
"        function prev_node()\n"
"        {\n"
"          if (previous_node.length !== 0)\n"
"          {  \n"
"            console.log(previous_node);\n"
"            var last_node = previous_node.pop();\n"
"            populateList(last_node);\n"
"          }\n"
"        }\n"
"        function downloadAllFiles(directory){\n"
"          const fileUrls = [];\n"
"\n"
"          function collectFileUrls(file) {\n"
"            if (file.files && file.files.length !== 0)\n"
"            {\n"
"              file.files.forEach((subFile) => { collectFileUrls(subFile); }); \n"
"            }\n"
"            else \n"
"            {\n"
"              fileUrls.push(file.url);\n"
"            }\n"
"          }\n"
"\n"
"          collectFileUrls(directory);\n"
"\n"
"          fileUrls.forEach((url) => {\n"
"            const link = document.createElement('a');\n"
"            link.href = url;\n"
"            link.download = '';\n"
"            document.body.appendChild(link);\n"
"            link.click();\n"
"            document.body.removeChild(link);\n"
"          })\n"
"        }\n"
"        fetchJSONData();\n"
"      </script>\n"
"	  <ul id=\"list\">\n"
"	  </ul>\n"
"    \n"
"    </div>\n"
"  </body>\n"
"</html>\n"
;